[profile.default]
# Configuration for nextest
retries = 1
slow-timeout = "60s"
leak-timeout = "100ms"

[profile.ci]
retries = 2
slow-timeout = "30s"

# Test threads configuration
test-threads = "logical"

# Output configuration
status-level = "retry"
final-status-level = "slow"

# Cargo options
cargo-metadata-timeout = "60s"

# Test grouping
[test-groups]
serial = { max-threads = 1 }

# Override specific tests that need serial execution
[[profile.default.overrides]]
filter = "test(filesystem::tests::test_list_volumes)"
test-group = "serial"

[[profile.default.overrides]]
filter = "test(security::tests::test_execute_safe_command)"
test-group = "serial"