name: Build Tauri Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

env:
  # Set environment variables for Android SDK and NDK paths
  ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
  ANDROID_NDK_HOME: ${{ github.workspace }}/android-sdk/ndk/25.2.9519653 # Or your preferred NDK version

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use an LTS version suitable for Tauri
          cache: 'pnpm' # Enable pnpm caching
          cache-dependency-path: './pnpm-lock.yaml' # Path to your pnpm-lock.yaml

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Frontend Dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up Java Development Kit
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          key: "${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}"
          restore-keys: |
            ${{ runner.os }}-rust-

      - name: Build Tauri Android App
        run: pnpm tauri build --target aarch64-linux-android --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-android-app
          path: src-tauri/target/aarch64-linux-android/release/*.apk